Test integration
Tapestry-Pooling/tapestry-webapp pull request #43
Opened 2020-09-07 18:49 UTC by prantik1998

2020-09-16 04:43 UTC, sunitakawane requested changes

2020-09-16 04:43 UTC, sunitakawane commented on src/components/Error/User/newuser.js
> +                        window.location.href = url.BASE_FRONTEND_URL +"login"
check if you should use BASE_FRONTEND_URL , for errors in dev/prod environment , the redirect should not be to localhost. use relative path here

2020-09-16 04:43 UTC, sunitakawane commented on src/constants/url.js
> +  BASE_FRONTEND_URL: "http://localhost:3000/",
do not use BASE_FRONTEND_URL / localhost for redirect

2020-09-17 21:27 UTC, prantik1998 commented on src/constants/url.js
> +  BASE_FRONTEND_URL: "http://localhost:3000/",
what should I use then??

2020-09-18 03:30 UTC, merged